image:
  name: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  TF_VAR_gitlab_token: ${GITLAB_ACCESS_TOKEN}
  AWS_ACCESS_KEY_ID: ${MY_AWS_KEY}
  AWS_SECRET_ACCESS_KEY: ${MY_AWS_ACCESS_KEY}
  AWS_DEFAULT_REGION: "us-east-1"

  # Database-related variables
  TF_VAR_DB_HOST: "mainrdsinstance.ctioco2e8nas.us-east-1.rds.amazonaws.com"
  TF_VAR_DB_USER: "mainrdsuser"
  TF_VAR_DB_PASSWORD_PARAM: "myrdspassword"
  TF_VAR_DB_PORT: "3306"
  TF_VAR_DB_NAME: "maindb"
  TF_VAR_tag_value: "TerraformAWSCloudInfraAutomationProject"
  TF_VAR_vpc_id_main: "vpc-0bc357960595a0f4a"

cache:
  paths:
    - .terraform  # Cache the Terraform provider plugins directory

before_script:
  - terraform --version
  - |
    terraform init \
      -backend-config="bucket=terraformbackend-v" \
      -backend-config="key=statefile" \
      -backend-config="region=us-east-1" \
      -backend-config="dynamodb_table=terraformbackend" \
      -reconfigure

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate
  artifacts:
    paths:
      - terraform.lock.hcl
      - .terraform  # Cache Terraform plugins directory

plan:
  stage: plan
  script:
    - terraform plan -out="planfile" -lock=false  # remove -lock=false when using in multi-environment
  dependencies:
    - validate
  artifacts:
    paths:
      - terraform.lock.hcl
      - planfile
      - .terraform  # Cache Terraform plugins directory

apply:
  stage: apply
  script:
    - terraform apply -input=false -lock=true "planfile" # replace false with true when multi-users managing the terraform workspace
  dependencies:
    - plan
  when: manual  # Set apply stage to manual execution
  artifacts:
    paths:
      - terraform.lock.hcl
      - .terraform  # Cache Terraform plugins directory

destroy:
  stage: destroy
  script:
    - terraform destroy --auto-approve -lock=true  # replace false with true when multi-users managing the terraform workspace
  dependencies:
    - apply
  when: manual  # Set destroy stage to manual execution
  artifacts:
    paths:
      - terraform.lock.hcl
